const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const renderer = fs.readFileSync(path.join(root, 'src', 'renderer.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'src', 'index.html'), 'utf8');
const main = fs.readFileSync(path.join(root, 'main.js'), 'utf8');
const preload = fs.readFileSync(path.join(root, 'preload.js'), 'utf8');

assert(renderer.includes('maxPairs: 20'), 'Training debe permitir hasta 20 modelos/pares activos.');
assert(renderer.includes("minMt5Pairs: 6"), 'Training debe priorizar candidatos MT5 cuando existan.');
assert(renderer.includes('targetOpenPositions: 20'), 'Training debe mantener 20 posiciones demo continuas.');
assert(renderer.includes('targetIntradayPositions: 10'), 'Training debe mantener 10 modelos intradia.');
assert(renderer.includes('targetSwingPositions: 10'), 'Training debe mantener 10 modelos de mediano plazo.');
assert(renderer.includes('maintainTrainingExposure'), 'Training debe abrir operaciones demo de aprendizaje continuo.');
assert(renderer.includes('exploration_paper'), 'Training debe tener exploracion paper cuando no haya setup perfecto.');
assert(renderer.includes("executeRealTrade()"), 'Debe existir separacion explicita de ejecucion real.');
assert(renderer.includes("executeSimulatedTrade("), 'Training debe usar ejecucion simulada separada.');
assert(renderer.includes("min_hold_ms"), 'Las operaciones demo deben tener hold minimo.');
assert(renderer.includes("horizon === 'swing'"), 'Debe existir horizonte swing/mediano plazo.');
assert(renderer.includes('trainingContext()'), 'El chat debe conocer el estado real del Training.');
assert(renderer.includes('macroContext()'), 'El chat debe recibir contexto macro/news.');
assert(renderer.includes('macroRiskLevel'), 'Training y senales deben calcular riesgo macro/news.');
assert(renderer.includes('currentNewsContext(pair.symbol)'), 'Cada trade/leccion debe registrar contexto de noticias/macro.');
assert(renderer.includes('Buen momento para comprar') && renderer.includes('Buen momento para vender'), 'El medidor IA debe mostrar compra/venta cuando la direccion y confianza sean suficientes.');
assert(renderer.includes('riesgo macro alto'), 'El riesgo macro alto debe marcar cautela sin ocultar una senal fuerte.');
assert(renderer.includes('ictCrtScore'), 'Training debe incorporar scoring ICT/CRT.');
assert(renderer.includes('crtWeeklyBias'), 'Training debe analizar sesgo CRT semanal.');
assert(renderer.includes('scoreStrategyPortfolio'), 'Training debe comparar un portafolio de estrategias, no solo ICT/CRT.');
assert(renderer.includes('trainingSignalId'), 'Cada senal nueva debe generar signal_id estable y auditable.');
assert(renderer.includes('buildTrainingTraceMetadata'), 'Training debe construir metadata causal para senales/posiciones nuevas.');
assert(renderer.includes('entry_reason_code'), 'Las posiciones nuevas deben persistir entry_reason_code cuando este disponible.');
assert(renderer.includes('risk_profile_id'), 'Las posiciones nuevas deben persistir risk_profile_id para trazabilidad.');
assert(renderer.includes('confidence_at_entry'), 'Las posiciones nuevas deben conservar confidence_at_entry.');
assert(renderer.includes('signal_id: trace.signal_id'), 'Las posiciones nuevas deben copiar signal_id desde la metadata causal.');
assert(renderer.includes('source: trace.source'), 'Las posiciones nuevas deben preservar el source causal.');
assert(html.includes('services/training-closure-service.js'), 'Renderer debe cargar el wrapper del Training Closure Service antes de cerrar trades.');
assert(renderer.includes('window.QuantTrainingClosure.buildClosedTradeFromPosition'), 'El cierre de trades debe delegar la construccion al Training Closure Service.');
assert(renderer.includes('lessonBuilder'), 'El cierre delegado debe seguir generando lecciones con el builder actual.');
assert(renderer.includes('scoreTrendMomentum') && renderer.includes('scoreBreakoutRetest') && renderer.includes('scoreMeanReversion') && renderer.includes('scoreVolumePullback'), 'Training debe testear trend, breakout, mean reversion y volume pullback.');
assert(renderer.includes('primaryStrategy'), 'Cada señal de training debe registrar estrategia dominante.');
assert(html.includes('chat-dock') && html.includes('chatContextPanel'), 'El chat de Quant debe estar siempre visible como dock con contexto activo.');
assert(renderer.includes('trainingUnrealizedPnl'), 'La contabilidad debe incluir P&L flotante en equity demo.');
assert(main.includes('calendar-finnhub-economic'), 'Main debe exponer calendario economico de Finnhub.');
assert(main.includes('TIMEFRAME_W1'), 'MT5 debe soportar velas semanales para CRT.');
assert(preload.includes('finnhubEconomic'), 'Preload debe exponer calendario macro a renderer.');
assert(renderer.includes('formatQuantText'), 'Las respuestas de Quant deben renderizarse con formato visual enriquecido.');
assert(renderer.includes('runSelfAudit'), 'Quant debe tener auditoria interna de vulnerabilidades.');
assert(main.includes('startLocalWebServer'), 'Quant debe exponer localhost web.');
assert(main.includes('activeWebPort'), 'Localhost debe reportar el puerto activo/fallback.');
assert(main.includes('MT5 adapter disabled'), 'MT5 debe quedar aislado como adapter opcional.');
assert(main.includes("'TRAINING_BACKEND_WRITER_ENABLED'"), 'El backend debe permitir activar el writer demo por variable de entorno controlada.');
assert(main.includes('deepseek-reasoner') || main.includes('Qwen/Qwen2.5-72B-Instruct'), 'Debe existir ruta a modelo fuerte.');
assert(renderer.includes("trainingStateWrite"), 'El renderer debe persistir estado de training.');
assert(main.includes('quant_training_state.json'), 'El estado de training debe guardarse en archivo local.');
assert(preload.includes('trainingStateRead') && preload.includes('trainingStateWrite'), 'Preload debe exponer persistencia de training.');
assert(html.includes('trainingPositionsShortTable') && html.includes('trainingPositionsSwingTable'), 'La UI debe dividir posiciones intradia y mediano plazo.');
assert(html.includes('trainLevel') && html.includes('trainingLevelTable'), 'La UI debe mostrar progreso/nivel de Quant.');
assert(html.includes('0 / 20'), 'La UI debe mostrar 20 modelos activos esperados.');
assert(main.includes('user_api_config.json'), 'Las API keys deben persistirse por usuario, no en una configuracion global compartida.');
assert(main.includes("ensureUser('mateo'"), 'Debe existir usuario Mateo sembrado para pruebas de aislamiento.');
assert(main.includes('/api/api-config-read') && main.includes('/api/api-config-write'), 'Main debe exponer endpoints para leer/escribir APIs por sesion autenticada.');
assert(main.includes('/api/api-config-import-env') && main.includes('importApiConfigFromEnvForUser'), 'Main debe poder materializar APIs ya configuradas en .env al store persistente del usuario.');
assert(main.includes("key !== 'REAL_TRADING'"), 'La importacion desde .env no debe activar trading real por accidente.');
assert(main.includes('currentUserFromRequest'), 'Las rutas web deben resolver el usuario desde la cookie de sesion.');
assert(main.includes('apiConfigStatus'), 'El estado del sistema debe usar la configuracion efectiva del usuario autenticado.');
assert(renderer.includes('apiConfigRead') && renderer.includes('apiConfigWrite'), 'Renderer debe poder leer/escribir configuracion API por usuario.');
assert(html.includes('apiConfigForm'), 'Settings debe incluir formulario para guardar APIs por sesion.');
assert(main.includes('coinbaseKlinesFallback') && main.includes('coinbaseTickerFallback'), 'Debe existir fallback de mercado cuando Binance bloquea Cloud Run con HTTP 451.');
assert(main.includes('withMarketFallback'), 'Ticker y klines deben intentar fallback antes de romper las graficas/training.');
assert(main.includes('binanceWalletUnavailable'), 'Wallet debe seguir mostrando MT5 aunque Binance firmado este bloqueado por region.');
assert(main.includes("'MT5_ACCOUNT2_LOGIN'") && main.includes("'MT5_ACCOUNT2_PASSWORD'") && main.includes("'MT5_ACCOUNT2_SERVER'"), 'La configuracion por usuario debe persistir MT5 Demo como cuenta 2.');
assert(html.includes('apiMt5DemoLogin') && html.includes('apiMt5DemoPassword') && html.includes('apiMt5DemoServer'), 'Settings debe incluir campos separados para MT5 Demo.');
assert(renderer.includes("MT5_ACCOUNT2_LOGIN: 'apiMt5DemoLogin'"), 'Renderer debe guardar MT5 Demo en MT5_ACCOUNT2_*.');

console.log('training_static.test.js OK');
