const ENV_EXAMPLE = `# Core runtime
NODE_ENV=production
QUANT_WEB_PORT=47829
QUANT_DATA_DIR=quant_data

# Bot safety defaults
REAL_TRADING=false
MT5_CONNECTOR_ENABLED=false
DEFAULT_PROVIDER=deepseek

# Binance
BINANCE_API_KEY=
BINANCE_SECRET=

# AI providers
DEEPSEEK_API_KEY=
DEEPSEEK_BASE_URL=https://api.deepseek.com
DEEPSEEK_MODEL=deepseek-reasoner
DEEPINFRA_API_KEY=
DEEPINFRA_BASE_URL=https://api.deepinfra.com/v1/openai
DEEPINFRA_MODEL=Qwen/Qwen2.5-72B-Instruct
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=llama3.1

# Web auth
WEB_AUTH_ENABLED=true
WEB_AUTH_EMAIL=
WEB_AUTH_PASSWORD=

# Market/news
FINNHUB_API_KEY=
ALPHA_VANTAGE_API_KEY=

# Optional MT5 adapter
MT5_ACCOUNT1_LOGIN=
MT5_ACCOUNT1_PASSWORD=
MT5_ACCOUNT1_SERVER=
MT5_ACCOUNT2_LOGIN=
MT5_ACCOUNT2_PASSWORD=
MT5_ACCOUNT2_SERVER=
MT5_PYTHON_COMMAND=
MT5_BRIDGE_STATUS_FILE=
MT5_REAL_BRIDGE_STATUS_FILE=
MT5_REAL_TRADING_ENABLED=false
MT5_REAL_MAX_LOTS=0.02
MT5_REAL_DEVIATION=20
MT5_REAL_ORDER_TIMEOUT_MS=15000
MT5_REAL_RISK_PER_TRADE_PCT=10
MT5_REAL_TOTAL_RISK_PCT=25
MT5_REAL_EQUITY_GATE_DISABLED=false
MT5_REAL_ALLOW_UNPROTECTED_OPEN=false
MT5_DEMO_TRADING_ENABLED=false
MT5_DEMO_MAX_LOTS=0.05
TRAINING_MT5_DEMO_ORDER_SEND_ENABLED=false
TRAINING_MT5_DEMO_CLOSE_ENABLED=false
TRAINING_MT5_DEMO_LOT_SIZE=0.01

# Real autonomous scheduler
REAL_AUTONOMOUS_SCHEDULER_ENABLED=false
REAL_AUTONOMOUS_ALLOWED_VENUES=BINANCE,MT5
REAL_AUTONOMOUS_MAX_OPEN_POSITIONS=200
REAL_AUTONOMOUS_MAX_ORDERS_PER_TICK=20
REAL_AUTONOMOUS_MAX_ORDERS_PER_DAY=1000
REAL_AUTONOMOUS_STOP_LOSS_PCT=2
REAL_AUTONOMOUS_TAKE_PROFIT_PCT=3
REAL_AUTONOMOUS_MT5_ENABLED=false
REAL_AUTONOMOUS_MT5_LOTS=0.01
REAL_AUTONOMOUS_MT5_STOP_LOSS_PCT=0.25
REAL_AUTONOMOUS_MT5_TAKE_PROFIT_PCT=0.5

# Profit harvest: skim Spot USDT above the trading float into USDC Flexible Earn.
# Trades only Spot; never redeems Earn or touches Funding (only deposits to Earn).
REAL_AUTONOMOUS_PROFIT_HARVEST_ENABLED=false
REAL_AUTONOMOUS_TRADING_FLOAT_USDT=12
REAL_AUTONOMOUS_PROFIT_HARVEST_MIN_USDT=5
REAL_AUTONOMOUS_PROFIT_HARVEST_MAX_USDT=1000
REAL_AUTONOMOUS_PROFIT_HARVEST_EARN_PRODUCT=USDC001
MT5_PROTECTION_XAUUSD_MAX_STOP_LOSS_PCT=0.35
REAL_AUTONOMOUS_MT5_ALLOW_OVERNIGHT=false
REAL_AUTONOMOUS_MT5_MAX_HOLD_HOURS=22

# Optional sync
QUANT_SYNC_URL=
QUANT_SYNC_KEY=
`;

const SENSITIVE_KEY_PATTERN = /(KEY|SECRET|PASSWORD|PASS)/i;

function isSensitiveKey(key) {
  return SENSITIVE_KEY_PATTERN.test(String(key || ''));
}

function redactEnv(env = {}) {
  const redacted = {};
  for (const [key, value] of Object.entries(env)) {
    redacted[key] = isSensitiveKey(key) && value ? '***REDACTED***' : value;
  }
  return redacted;
}

module.exports = {
  ENV_EXAMPLE,
  isSensitiveKey,
  redactEnv
};
